environment:
  # See README for information on the token
  ANACONDA_TOKEN:
    secure: 2UnYf6VE6Tf1nTCUX4jV1cNDjMwFiXHCdI7cSlG74DI72EO5dEdmG3M8v32uwfQ3
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\scripts\\appveyor\\run_with_env.cmd"

  matrix:
#     - PYTHON: "C:\\Python27_32"
#       PYTHON_VERSION: "2.7"
#       PYTHON_ARCH: "32"
#       CONDA_PY: "27"

#     - PYTHON: "C:\\Python27_64"
#       PYTHON_VERSION: "2.7"
#       PYTHON_ARCH: "64"
#       CONDA_PY: "27"

#     - PYTHON: "C:\\Python35_32"
#       PYTHON_VERSION: "3.5"
#       PYTHON_ARCH: "32"
#       CONDA_PY: "35"

#     - PYTHON: "C:\\Python35_64"
#       PYTHON_VERSION: "3.5"
#       PYTHON_ARCH: "64"
#       CONDA_PY: "35"

#     - PYTHON: "C:\\Python36_32"
#       PYTHON_VERSION: "3.6"
#       PYTHON_ARCH: "32"
#       CONDA_PY: "36"

#     - PYTHON: "C:\\Python36_64"
#       PYTHON_VERSION: "3.6"
#       PYTHON_ARCH: "64"
#       CONDA_PY: "36"

#     - PYTHON: "C:\\Python37_32"
#       PYTHON_VERSION: "3.7"
#       PYTHON_ARCH: "32"
#       CONDA_PY: "37"

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\scripts\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Fix MSVS 2008 on x64
  - regedit /s x64\VC_OBJECTS_PLATFORM_INFO.reg
  - regedit /s x64\600dd186-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\600dd187-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\600dd188-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\600dd189-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\656d875f-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\656d8760-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\656d8763-2429-11d7-8bf6-00b0d03daa06.reg
  - regedit /s x64\656d8766-2429-11d7-8bf6-00b0d03daa06.reg
  - copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\AMD64.VCPlatform.config" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\AMD64.VCPlatform.Express.config"
  - copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\Itanium.VCPlatform.config" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\Itanium.VCPlatform.Express.config"
  - conda update -c conda-forge --no-channel-priority --all -y
  - conda install -c conda-forge -y libarchive
  - activate


build: false

test_script:
  # Build and test the package. This appears(?) to sporadically fail due to a
  # bug in conda-build on 32 bit python.
  # https://github.com/conda/conda-build/issues/152
  #
  # Note also that our setup.py script, which is called by conda-build, writes
  # a __conda_version__.txt file, so the version number on the binary package
  # is set dynamically. This unfortunately mean that conda build --output
  # doesn't really work.
  #
  - "%CMD_IN_ENV% conda build recipe -c openbabel"
  # Move the conda package into the current directory, to register it
  # as an "artifact" for Appveyor. cmd.exe does't have good globbing, so
  # we'll use a simple python script.
  - python .\\scripts\\appveyor\\move-conda-package.py recipe

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'

on_success:
  # Upload built binaries to binstar.org. The globbing and handling of the
  # exit-status code is tricky in cmd.exe or powershell, so we're just using
  # a python script.
  # don't upload now
  # - IF %APPVEYOR_REPO_BRANCH%==master (python scripts\appveyor\anaconda_push.py)
